[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-anime_room
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-anime_room
GtkTheme=oomox-anime_room
IconTheme=oomox-anime_room
MetacityTheme=oomox-anime_room
